-- Add Father Phone, Mother Phone, and Medium columns to Students table
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Students' AND COLUMN_NAME='FatherPhone')
BEGIN
    ALTER TABLE Students ADD FatherPhone NVARCHAR(20);
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Students' AND COLUMN_NAME='MotherPhone')
BEGIN
    ALTER TABLE Students ADD MotherPhone NVARCHAR(20);
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Students' AND COLUMN_NAME='Medium')
BEGIN
    ALTER TABLE Students ADD Medium NVARCHAR(50);
END
